apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
    version: v2
  name: reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: msbgsm/reverseproxy
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500Mi"
          ports:
            - containerPort: 8080
      restartPolicy: Always